# Generated by Django 4.0.5 on 2022-06-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='id_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
