# Generated by Django 4.0.5 on 2022-06-19 18:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_profile_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
